### ISSUE TITLE
Seeking new maintainer

### ISSUE THREAD

**Issue by rgaiacs** [rgaiacs/swc-shell-split-window#12]
Unfortunately, I haven't teach any workshop for The Carpentries since late 2019 and didn't use this project in the last 4+ years.  

If you are interested to be the new maintainer of this project, please contact me in this issue. I can give you write access or transfer this repository.

cc @dpshelio @paddyroddy

**Comment by dpshelio** [comment]
We would be happy to maintain it at @ucl-arc as we use it regularly on our teaching activities.

**Comment by rgaiacs** [comment]
> We would be happy to maintain it at https://github.com/UCL-ARC

I will transfer the repository.

**Comment by rgaiacs** [comment]
@dpshelio I couldn't transfer.

![Screenshot 2024-05-13 at 16-44-47 Transfer repository](https://github.com/rgaiacs/swc-shell-split-window/assets/1506457/c24946e3-669b-4d42-b0cd-e58f259b505a)

I'm trying to give you co-ownership for you to be able to transfer the repository.

**Comment by olexandr-konovalov** [comment]
Thanks for agreeing to take care of this @dpshelio! We also use it regularly, so I'm very interested for this to be maintained!

**Comment by dpshelio** [comment]
I've not seen any invitation, unless it expired when I was not paying attention :innocent:

**Comment by rgaiacs** [comment]
@dpshelio you have access.

![Screenshot 2024-08-22 at 10-22-15 Manage access](https://github.com/user-attachments/assets/929130f5-4dfa-4607-8a18-0cf4e2d8a068)

**Comment by dpshelio** [comment]
I see. I have write access, but I can't transfer it as I don't see the settings page. I think we will need first you to transfer to a new owner - me, and then I can transfer to UCL.

**Comment by rgaiacs** [comment]
@dpshelio I can't transfer to you.

![Screenshot 2024-08-22 at 16-46-37 Transfer repository](https://github.com/user-attachments/assets/8db61ea0-9e3c-4750-aa05-702c8b15ce50)

**Comment by dpshelio** [comment]
Ooohh.. becaues I have a fork! I've removed it now, you should be able to.

**Comment by rgaiacs** [comment]
@dpshelio 

>  Repository transfer to dpshelio requested

**Comment by dpshelio** [comment]
And it's now under UCL-ARC.  Thanks @rgaiacs we will keep it alive for very long!
