### ISSUE TITLE
Scroll function is lost

### ISSUE THREAD

**Issue by anelda** [rgaiacs/swc-shell-split-window#5]
Hi @rgaiacs 
Thanks so much for this! I saw it in action in one of our demo sessions and loved it.
I noticed however that the scroll function is lost - I can't use the mouse to scroll back up to previous commands and outputs.

Is this fixable? 

I run Ubuntu. Let me know if you need more information?

**Comment by rgaiacs** [comment]
Hi @anelda,

Sorry for the delay. December was busier than usual and I had to take some holidays.

> I noticed however that the scroll function is lost - I can't use the mouse to scroll back up to previous commands and outputs.
>
> Is this fixable?

This is tmux. :-/ You need to change to "Copy mode" with `Ctrl + b [` and use the arrow keys.

I will keep it open to add that information to the README.

**Comment by r-barnes** [comment]
Edit the file `~/.tmux.conf` to contain the line:

    setw -g mouse on

Now the mouse will scroll as expected.

**Comment by anelda** [comment]
This is great! Thanks!

**Comment by r-barnes** [comment]
Since a note has been added about this to README.md, I believe this issue can be closed.
